### ISSUE TITLE
Display correct user avatar

### ISSUE THREAD

**Issue by matevzmihalic** [wlanslovenija/PiplMesh#113] opened 2012-04-11 11:08 UTC
Currently we show users avatar from Facebook even if user didn't login with Facebook.

Change user avatar, to use gravatar if user isn't loged in with Facebook.

**Comment by mitar** [comment] 2012-04-11 18:36
Is not this duplicate of #63?

**Comment by matevzmihalic** [comment] 2012-04-11 18:41
Yes it is. I didn't find it before.

**Comment by mitar** [comment] 2012-04-11 19:41
Duplicate. Closing in favor of #63.

**Closed as completed by mitar** 2012-04-11 19:41 UTC
